import os
import unittest
from unittest.mock import patch

from app.core.config import get_settings
from app.schemas.story import GeneratedSlide, StoryGenerateRequest, StoryGenerateResponse
from app.services.backend_mapper import (
    map_generate_request_to_pipeline,
    map_story_to_generate_response,
)
from generators.story.story_model import Page, Story


class TestBackendIntegrationContract(unittest.TestCase):
    def setUp(self) -> None:
        self.env_patcher = patch.dict(
            os.environ,
            {"MORETALE_STORY_PAGE_COUNT": "3"},
            clear=False,
        )
        self.env_patcher.start()
        self.addCleanup(self.env_patcher.stop)

    def test_story_generate_request_accepts_swagger_payload(self) -> None:
        request = StoryGenerateRequest.model_validate(
            {
                "prompt": "토끼와 거북이가 우주로 여행을 떠나는 이야기",
                "profileId": 1,
                "childName": "민준",
                "primaryLanguage": "ko",
                "secondaryLanguage": "vi",
                "ageGroup": "AGE_5_6",
                "childAge": 5,
                "firstLanguageProficiency": "BEE",
                "secondLanguageProficiency": "LARVA",
                "firstLanguageListening": "BEE",
                "firstLanguageSpeaking": "PUPA",
                "secondLanguageListening": "LARVA",
                "secondLanguageSpeaking": "EGG",
                "storyPreference": "FUN_ADVENTURE",
                "customStoryPreference": "우주 탐험 이야기",
                "autoGenerated": False,
                "recommendedTaleTitle": "흥부와 놀부",
            }
        )

        self.assertEqual(request.profile_id, 1)
        self.assertEqual(request.primary_language, "ko")
        self.assertEqual(request.secondary_language, "vi")
        self.assertEqual(request.age_group, "AGE_5_6")

        pipeline = map_generate_request_to_pipeline(request)
        self.assertEqual(pipeline.child_name, "민준")
        self.assertEqual(pipeline.child_age, 5)
        self.assertEqual(pipeline.primary_lang, "Korean")
        self.assertEqual(pipeline.secondary_lang, "Vietnamese")
        self.assertEqual(pipeline.page_count, 3)
        self.assertIn("흥부와 놀부", pipeline.extra_prompt)

    def test_backend_story_page_count_uses_env_for_every_age_group(self) -> None:
        cases = [
            "AGE_0_2",
            "AGE_3_4",
            "AGE_5_6",
            "AGE_7_8",
            "AGE_9_10",
            "AGE_10_PLUS",
        ]

        for age_group in cases:
            with self.subTest(age_group=age_group):
                request = StoryGenerateRequest.model_validate(
                    {
                        "prompt": "friendship",
                        "childName": "Mina",
                        "primaryLanguage": "ko",
                        "secondaryLanguage": "en",
                        "ageGroup": age_group,
                    }
                )

                pipeline = map_generate_request_to_pipeline(request)

                self.assertEqual(pipeline.page_count, 3)

    def test_backend_story_page_count_env_can_change_without_age_policy(self) -> None:
        with patch.dict(os.environ, {"MORETALE_STORY_PAGE_COUNT": "16"}, clear=False):
            request = StoryGenerateRequest.model_validate(
                {
                    "prompt": "friendship",
                    "childName": "Mina",
                    "primaryLanguage": "ko",
                    "secondaryLanguage": "en",
                    "ageGroup": "AGE_0_2",
                }
            )

            pipeline = map_generate_request_to_pipeline(request)

        self.assertEqual(pipeline.page_count, 16)

    def test_story_page_count_env_is_required(self) -> None:
        env = {
            key: value
            for key, value in os.environ.items()
            if key != "MORETALE_STORY_PAGE_COUNT"
        }
        with patch.dict(os.environ, env, clear=True):
            with self.assertRaises(ValueError):
                get_settings()

    def test_story_page_count_env_must_be_valid(self) -> None:
        for value in ("0", "33", "abc"):
            with self.subTest(value=value):
                with patch.dict(
                    os.environ,
                    {"MORETALE_STORY_PAGE_COUNT": value},
                    clear=False,
                ):
                    with self.assertRaises(ValueError):
                        get_settings()

    def test_story_request_accepts_optional_profile_context_from_story_init(self) -> None:
        request = StoryGenerateRequest.model_validate(
            {
                "prompt": "따뜻한 가족 이야기",
                "childName": "Mina",
                "primaryLanguage": "ko",
                "secondaryLanguage": "en",
                "familyStructure": "ONE_PARENT",
                "childNationality": "KR",
                "parentCountry": "VN",
            }
        )

        pipeline = map_generate_request_to_pipeline(request)
        self.assertEqual(pipeline.family_situation, "single_parent")
        self.assertIn("one-parent family", pipeline.extra_prompt)
        self.assertIn("Child nationality: KR", pipeline.extra_prompt)
        self.assertIn("Parent country: VN", pipeline.extra_prompt)

    def test_story_generate_response_serializes_to_backend_camel_case(self) -> None:
        response = StoryGenerateResponse(
            title="Mina's Adventure",
            child_name="Mina",
            primary_language="ko",
            secondary_language="en",
            slides=[
                GeneratedSlide(
                    order=0,
                    text_kr="안녕",
                    text_native="hello",
                    image_url=None,
                    audio_url_kr=None,
                    audio_url_native=None,
                )
            ],
        )

        payload = response.model_dump(mode="json", by_alias=True)
        self.assertEqual(payload["childName"], "Mina")
        self.assertEqual(payload["slides"][0]["textKr"], "안녕")
        self.assertEqual(payload["slides"][0]["textNative"], "hello")

    def test_story_response_language_codes_are_lowercase_iso(self) -> None:
        story = Story(
            title_primary="제목",
            title_secondary="Title",
            author_name="Mina",
            primary_language="Korean",
            secondary_language="English",
            image_style="storybook",
            main_character_design="child",
            pages=[
                Page(
                    page_number=index,
                    text_primary=f"문장 {index}",
                    text_secondary=f"Sentence {index}",
                    illustration_prompt=f"Scene {index}",
                )
                for index in range(1, 33)
            ],
        )

        for language_input in ("KO", "ko", "Korean"):
            with self.subTest(language_input=language_input):
                request = StoryGenerateRequest.model_validate(
                    {
                        "prompt": "friendship",
                        "childName": "Mina",
                        "primaryLanguage": language_input,
                        "secondaryLanguage": "EN",
                    }
                )
                payload = map_story_to_generate_response(story, request).model_dump(
                    mode="json",
                    by_alias=True,
                )

                self.assertEqual(payload["primaryLanguage"], "ko")
                self.assertEqual(payload["secondaryLanguage"], "en")

    def test_story_response_slide_order_is_zero_based_for_backend(self) -> None:
        story = Story(
            title_primary="제목",
            title_secondary="Title",
            author_name="Mina",
            primary_language="Korean",
            secondary_language="English",
            image_style="storybook",
            main_character_design="child",
            pages=[
                Page(
                    page_number=index,
                    text_primary=f"문장 {index}",
                    text_secondary=f"Sentence {index}",
                    illustration_prompt=f"Scene {index}",
                )
                for index in range(1, 4)
            ],
        )
        request = StoryGenerateRequest.model_validate(
            {
                "prompt": "friendship",
                "childName": "Mina",
                "primaryLanguage": "ko",
                "secondaryLanguage": "en",
            }
        )

        payload = map_story_to_generate_response(story, request).model_dump(
            mode="json",
            by_alias=True,
        )

        self.assertEqual([slide["order"] for slide in payload["slides"]], [0, 1, 2])

    def test_story_response_prepends_cover_slide_when_cover_asset_exists(self) -> None:
        story = Story(
            title_primary="제목",
            title_secondary="Title",
            author_name="Mina",
            primary_language="Korean",
            secondary_language="English",
            image_style="storybook",
            main_character_design="child",
            pages=[
                Page(
                    page_number=index,
                    text_primary=f"문장 {index}",
                    text_secondary=f"Sentence {index}",
                    illustration_prompt=f"Scene {index}",
                )
                for index in range(1, 3)
            ],
        )
        request = StoryGenerateRequest.model_validate(
            {
                "prompt": "friendship",
                "childName": "Mina",
                "primaryLanguage": "ko",
                "secondaryLanguage": "en",
            }
        )

        payload = map_story_to_generate_response(
            story,
            request,
            page_assets={
                0: {"image_url": "/cover.png", "audio_url_kr": None, "audio_url_native": None},
                1: {
                    "image_url": "/page_01.png",
                    "audio_url_kr": "/page_01_kr.wav",
                    "audio_url_native": "/page_01_en.wav",
                },
            },
        ).model_dump(mode="json", by_alias=True)

        self.assertEqual([slide["order"] for slide in payload["slides"]], [0, 1, 2])
        self.assertEqual(payload["slides"][0]["imageUrl"], "/cover.png")
        self.assertEqual(payload["slides"][0]["textKr"], "")
        self.assertEqual(payload["slides"][0]["textNative"], "")
        self.assertIsNone(payload["slides"][0]["audioUrlKr"])
        self.assertEqual(payload["slides"][1]["imageUrl"], "/page_01.png")
        self.assertEqual(payload["slides"][1]["audioUrlKr"], "/page_01_kr.wav")


if __name__ == "__main__":
    unittest.main()
